# 2 Linear Equations and Computer Basics

In [2]:
#%pylab inline
%pylab notebook
# pylab Populating the interactive namespace from numpy and matplotlib
# numpy for numerical computation
# matplotlib for ploting

/opt/conda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/opt/conda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


Populating the interactive namespace from numpy and matplotlib


In [17]:
from numpy import append, array, diagonal, tril, triu
from numpy.linalg import inv, solve
from scipy.linalg import lu
from pprint import pprint
from numpy import array, zeros, diag, diagflat, dot


## 2.1 Computer Arithmetic

Some knowledge of how computers perform numerical computations and how programming
languages work is useful in applied numerical work, especially if one is to
write efficient programs and avoid errors. It often comes as an unpleasant surprise to
many people to learn that exact arithmetic and computer arithmetic do not always
give the same answers, even in programs without programming errors.

Typically, computer languages such as Fortran and C allow several ways of representing
a number.

The exact details of the representation depends on the hardware but it will
suffice for our purposes to suppose that floating point numbers are stored in the form
$m2^e$, where m and e are integers with $-2^b <= m <2^b$ and $-2^d <= e < 2^d$.

The obvious way of computing this term will result in loss of precision.

These arise not only from overflow but from division by 0.

In addition,floating point numbers may get set to $NaN$, which stands for not-anumber.

Roundoff error is only one of the pitfalls in evaluating mathematical expressions.
In numerical computations, error is also introduced by the computer's inherent inability
to evaluate certain mathematical expressions exactly. For all its power, a computer
can only perform a limited set of operations in evaluating expressions. Essentially this
list includes the four arithmetic operations of addition, subtraction, multiplication
and division, as well as logical operations of comparison.

Other common functions,such as exponential, logarithmic, and trigonometric functions cannot be evaluated directly using computer arithmetic. They can only be evaluated approximately using algorithms based on the four basic arithmetic operations.

For the common functions very efficient algorithms typically exist and these are
sometimes "hardwired" into the computer's processor or coprocessor. An important
area of numerical analysis involves determining efficient approximations that can be
computed using basic arithmetic operations.



$$exp(x) = \sum^{inf}_{i=0} x^{n}/n!$$

Obviously one cannot compute the infinite sum, but one could compute a finite number
of these terms, with the hope that one will obtain sufficient accuracy for the
purpose at hand. The result, however, will always be inexact.

## 2.3 Linear Equations and the L-U Factorization

The linear equation is the most elementary problem that arises in computational
economic analysis. In a linear equation, an $n \times n$ matrix A and an n-vector b are
given, and one must compute the n-vector x that satisfies

$$A x = b$$

In [34]:
# example problem

A = np.array([[4.0, -2.0, 1.0], [1.0, -3.0, 2.0], [-1.0, 2.0, 6.0]])

b = [1.0, 2.0, 3.0]

x0 = [1.0, 1.0, 1.0]

n = 25


print( "A:")
pprint(A)


print( "diag(A):")
pprint(diagflat(diag(A)))


print( "b:")
pprint(b)

print( "x0:")
pprint(x0)

print( "n:")
pprint(n)


A:
array([[ 4., -2.,  1.],
       [ 1., -3.,  2.],
       [-1.,  2.,  6.]])
diag(A):
array([[ 4.,  0.,  0.],
       [ 0., -3.,  0.],
       [ 0.,  0.,  6.]])
b:
[1.0, 2.0, 3.0]
x0:
[1.0, 1.0, 1.0]
n:
25


In [16]:
"""
Solve a linear equation by LU-decomposition
Comes from LU decomposition of a matrix A s.t. A = LU
Then
LUx = b => Ux = y => Ly = b
"""
_, l, u = lu(A)

Lower triangle matrix

In [18]:
l

array([[ 1.  ,  0.  ,  0.  ],
       [ 0.25,  1.  ,  0.  ],
       [-0.25, -0.6 ,  1.  ]])

Upper triangle matrix

In [21]:
u

array([[ 4.  , -2.  ,  1.  ],
       [ 0.  , -2.5 ,  1.75],
       [ 0.  ,  0.  ,  7.3 ]])

Forward solving

In [23]:
y = solve(l, b)
y    

array([ 1.  ,  1.75,  4.3 ])

Backward solving

In [25]:
x=solve(u, y)
x

array([-0.04109589, -0.28767123,  0.5890411 ])

### Jacobi-Method


The Jacobi method is a matrix iterative method used to solve the equation Ax=b for a known square matrix A of size n×n and known vector b or length n.

$$\begin{eqnarray*}
Ax = b
\end{eqnarray*}$$

A is split into the sum of two separate matrices, D and R, such that A=D+R. Dii=Aii, but Dij=0, for i≠j. R is essentially the opposite. Rii=0, but Rij=Aij for i≠j. The solution to the equation, i.e. the value of x

, is given by the following iterative equation:

$$\begin{eqnarray*}
x^{(k+1)} = D^{-1}(b-Rx^{(k)}).
\end{eqnarray*}$$





https://www.quantstart.com/articles/Jacobi-Method-in-Python-and-NumPy







Check result with direct method

In [40]:
def gauss_jacobi(A, b, iterations, x0=None):
    """
    Solve a linear equation by the gauss jacobi iteration outlined in the book.
    Follows the eq:
        x = inv(D)(b - Rx)
    Where D is the diagonal matrix of A and R is the remainder s.t D + R = A
    """
    d = diagflat(diag(A))
    # Calculate the remainder matrix
    r = A - d
    # If we have not provided an initial array for x make a new one
    if not x0:
        x = array([1 for _ in range(a.shape[1])])
    else:
        x = x0
    for _ in range(iterations):
        x = inv(d).dot(b - r.dot(x))
    return x


In [41]:
gauss_jacobi(A, b, n, x0)

array([-0.04109589, -0.28767124,  0.5890411 ])

In [35]:
solve(A,b)

array([-0.04109589, -0.28767123,  0.5890411 ])

### gauss seidel method






http://austingwalters.com/gauss-seidel-method/




Using the Gauss-Seidel Method

The method is fairly straight forward, given a standard system of linear equations, Ax = b. Where, A is a matrix (often representing a series of equations), x is a vector of x variables (Gauss-Seidel method is used to solve this vector) and b is the solution vector. In Gauss-Seidel method, we then split the A matrix into Upper (U) and Lower (L) matrices (the lower matrix in this case also contains the diagonal), then iterate using the following method:



![](http://108.61.119.12/wp-content/uploads/2014/05/gauss-equation.png)


https://github.com/mmcky/nyu-econ-370/blob/master/notebooks/notes-linear-algebra.ipynb



In [36]:
tril(A)

array([[ 4.,  0.,  0.],
       [ 1., -3.,  0.],
       [-1.,  2.,  6.]])

In [37]:
triu(A)

array([[ 4., -2.,  1.],
       [ 0., -3.,  2.],
       [ 0.,  0.,  6.]])

In [45]:
"""
ace.solvers
~~~~~~~~~~~
author:  hahnicity
https://github.com/hahnicity/ace/blob/master/ace/solvers.py
Solve a simple linear equation Ax = b in a particular way
"""



def gauss_seidel(A, b, iterations, x0=None):
    """
    Solve a linear equation by the gauss seidel iteration outlined in the book
    Follows the eq:
        x = inv(L)*(b - U*x)
    """
    l = tril(A)
    upper_plus_diagonal = triu(A)
    u = upper_plus_diagonal - diagflat(diag(A))
    # If we have not provided an initial array for x make a new one
    if not x0:
        x = array([1 for _ in range(a.shape[1])])
    else:
        x = x0

    for _ in range(iterations):
        x = inv(l).dot(b - u.dot(x))
    return x




gauss_seidel(A, b, n, x0)




array([-0.04109589, -0.28767123,  0.5890411 ])

In [31]:
def jacobi(A,b,N=25,x0=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x0 is None:
        x = zeros(len(A[0]))
    else:
        x = x0
    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)

    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

sol = jacobi(A,b,N=n,x0=x0)

print("x:")
pprint(sol)

x:
array([-0.04109589, -0.28767124,  0.5890411 ])


In [44]:
diag(A)

array([[ 4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -3.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  6.]])




https://www3.nd.edu/~zxu2/acms40390F12/Lec-7.3.pdf

http://austingwalters.com/gauss-seidel-method/


https://stackoverflow.com/questions/17580666/improving-numpy-speed-for-gauss-seidel-jacobi-solver